
$version="3.2.13"


/*numu dis*/
energy(#dis_nue)<>
include "./exp/smr/DUNE_dis_smear_nue_nominal.dat"
energy(#dis_numu)<>
include "./exp/smr/DUNE_dis_smear_numu_nominal.dat"
energy(#dis_nut)<>
include "./exp/smr/DUNE_dis_smear_nut_nominal.dat"
energy(#dis_anue)<>
include "./exp/smr/DUNE_dis_smear_anue_nominal.dat"
energy(#dis_anumu)<>
include "./exp/smr/DUNE_dis_smear_anumu_nominal.dat"
energy(#dis_anut)<>
include "./exp/smr/DUNE_dis_smear_anut_nominal.dat"
energy(#dis_NC)<>
include "./exp/smr/DUNE_dis_smear_NC_nominal.dat"

/*nue app*/
energy(#app_nue)<>
include "./exp/smr/DUNE_app_smear_nue_nominal.dat"
energy(#app_numu)<>
include "./exp/smr/DUNE_app_smear_numu_nominal.dat"
energy(#app_nut)<>
include "./exp/smr/DUNE_app_smear_nut_nominal.dat"
energy(#app_anue)<>
include "./exp/smr/DUNE_app_smear_anue_nominal.dat"
energy(#app_anumu)<>
include "./exp/smr/DUNE_app_smear_anumu_nominal.dat"
energy(#app_anut)<>
include "./exp/smr/DUNE_app_smear_anut_nominal.dat"
energy(#app_NC)<>
include "./exp/smr/DUNE_app_smear_NC_nominal.dat"

